### 1. What are the key features of Python?
- Python is free  and open-source.
- It is an object-oriented language.
- Easy to learn due to its clear syntax and readability.
- Easy to interpret, making debugging very easy.
- Easily integrated with other languages like C++, Java and more.
***

### 2. What are Keywords in Python?
- Keywords are reserved words which are used as identifiers, function names and more.
- They  help define the structuure and syntax of the language.
- There are **33 keywords** in python 3.7 and here are some of them.
- **Keywords:** False, None, True, and, break, if, else, for, return, continue, def etc.
***

### 3. What are literals in Python?
- Literals in Python refer to the data that is given in a variable or constant.
- There are **four** types of literals:
    - **String** literals - Sequence of characters enclosedd in quotes
    - **Numeric** literals - Integer, float and compplexx numbers
    - **Boolean** literals - Represents TRUE or FALSE
    - **Special** literals - 'None' is a good example
---

### 4. How can you concatenate two tuples?
- **Consider two tuples:**
    - tup1 = (1,"a",True)
    - tup2 = (4,5,6)

In [1]:
tup1 = (1,"a",True)
tup2 = (4,5,6)
print(tup1 + tup2)

(1, 'a', True, 4, 5, 6)


---

### 5. What are functions in Python?
- Functions in Python refer to **blocks** that  are organized, reusable pieces of code that perform single, and related events.
- Functions are important to create better modularity for applications which reuse high degree of coding.
- Python has a number of built-in functions like **print()** and allows of user-defined functions as well.
---

### 6. How can you initialize a 5*5 NumPy array with only zeroes?
- NummPy has a brilliant function - **zeros()** that does exactly this
- n1 = np.zeros((5,5))

In [1]:
import numpy as np

n1 = np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---