### 1. What are the key features of Python?
- Python is free  and open-source.
- It is an object-oriented language.
- Easy to learn due to its clear syntax and readability.
- Easy to interpret, making debugging very easy.
- Easily integrated with other languages like C++, Java and more.
***

### 2. What are Keywords in Python?
- Keywords are reserved words which are used as identifiers, function names and more.
- They  help define the structuure and syntax of the language.
- There are **33 keywords** in python 3.7 and here are some of them.
- **Keywords:** False, None, True, and, break, if, else, for, return, continue, def etc.
***

### 3. What are literals in Python?
- Literals in Python refer to the data that is given in a variable or constant.
- There are **four** types of literals:
    - **String** literals - Sequence of characters enclosedd in quotes
    - **Numeric** literals - Integer, float and compplexx numbers
    - **Boolean** literals - Represents TRUE or FALSE
    - **Special** literals - 'None' is a good example
---

### 4. How can you concatenate two tuples?
- **Consider two tuples:**
    - tup1 = (1,"a",True)
    - tup2 = (4,5,6)

In [1]:
tup1 = (1,"a",True)
tup2 = (4,5,6)
print(tup1 + tup2)

(1, 'a', True, 4, 5, 6)


---

### 5. What are functions in Python?
- Functions in Python refer to **blocks** that  are organized, reusable pieces of code that perform single, and related events.
- Functions are important to create better modularity for applications which reuse high degree of coding.
- Python has a number of built-in functions like **print()** and allows of user-defined functions as well.
---

### 6. How can you initialize a 5*5 NumPy array with only zeroes?
- NummPy has a brilliant function - **zeros()** that does exactly this
- n1 = np.zeros((5,5))

In [1]:
import numpy as np

n1 = np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---

### 7. What is Pandas?
- Pandas is an **open-source library** that has a very rich set of data structure for data based operations.
- Pandas can deal with a **large variety of files** and is one of the most important tools to have a grip on.
- It provides two fantastic data structure- **Series and DataFrames**
---

### 8. What are DataFrames?
- DataFrames are **mutable datatypes** present in the Pandas library.
- Provides support for heterogeneous data
- Here is how a **CSV file** can be read using Pandas:
    - df=pd.read_csv("mydata.csv")
    

In [2]:
import pandas as pd
df = pd.read_csv("matches.csv")
df.head(5)

id  season       city      date                        team1  \
0   1    2017  Hyderabad  5/4/2017          Sunrisers Hyderabad   
1   2    2017       Pune  6/4/2017               Mumbai Indians   
2   3    2017     Rajkot  7/4/2017                Gujarat Lions   
3   4    2017     Indore  8/4/2017       Rising Pune Supergiant   
4   5    2017  Bangalore  8/4/2017  Royal Challengers Bangalore   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1       Rising Pune Supergiant       Rising Pune Supergiant         field   
2        Kolkata Knight Riders        Kolkata Knight Riders         field   
3              Kings XI Punjab              Kings XI Punjab         field   
4             Delhi Daredevils  Royal Challengers Bangalore           bat   

   result  dl_applied                       winner  win_by_runs  \
0  normal           0          Sunrisers Hyderabad           35   
1  normal           0       Rising Pune Supergiant            0   
2  normal           0        Kolkata Knight Riders            0   
3  normal           0              Kings XI Punjab            0   
4  normal           0  Royal Challengers Bangalore           15   

   win_by_wickets player_of_match                                      venue  \
0               0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal   
1               7       SPD Smith    Maharashtra Cricket Association Stadium   
2              10         CA Lynn     Saurashtra Cricket Association Stadium   
3               6      GJ Maxwell                     Holkar Cricket Stadium   
4               0       KM Jadhav                      M Chinnaswamy Stadium   

          umpire1        umpire2  umpire3  
0     AY Dandekar       NJ Llong      NaN  
1  A Nand Kishore         S Ravi      NaN  
2     Nitin Menon      CK Nandan      NaN  
3    AK Chaudhary  C Shamshuddin      NaN  
4             NaN            NaN      NaN

---

### 9. What is a Pandas Series?
- Series is a **one-dimensional Panndas data structure** that supports data of almost any  type.
- It support multiple operations and is used for single dimensional data operations. 

In [3]:
import pandas as pd
data = ["1", 2, "three", 4.0]

series = pd.Series(data)

print(series)
print(type(series))

0        1
1        2
2    three
3      4.0
dtype: object
<class 'pandas.core.series.Series'>


---

### 10. What is the useof Pandas groupby() function?
- Groupby is a feature supported by pandas wich is used to **spilt and group** an object.
- Like the SQL, MySQL and Oracle groupby, it used to group data by classes and entities which can be further used for aggregation.

In [4]:
df = pd.DataFrame({'Vehicle': ['Kia', 'Lamborghini', 'KTM RC390', 'Unicorn 160'], 'Type': ["car", "car", "Bike", "Bike"]})
print(df)

       Vehicle  Type
0          Kia   car
1  Lamborghini   car
2    KTM RC390  Bike
3  Unicorn 160  Bike


In [5]:
df.groupby('Type').count()

Vehicle
Type         
Bike        2
car         2

---